project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Stephanie Cheng"
  site-url: "https://skycheng17.github.io/test_portfolio"
  repo-url: "skycheng17.github.io/test_portfolio"
  repo-actions: [source]
  description: "Urban Planner and Data Scientist"
  favicon: images/cell_towers.png
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: true
  search: 
    location: navbar
    type: overlay
  comments: 
    utterances: 
      repo: skycheng17/test_portfolio
      label: utterances
      theme: body-light
      issue-term: title
 
  navbar:
    right:
      - text: Portfolio
        aria-label: "Portfolio"
        href: "portfolio/portfolio.qmd"
  
  page-footer:  
    center: >-
     &#169; 2024 Stephanie Cheng &#8729; Made with ❤️ and [Quarto](https://quarto.org)

format: 
  html: 
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5rem
    link-external-newwindow: true
    theme:
      light: flatly
      dark: darkly
    highlight-style: solarized
    code-link: true
    code-copy: true
    toc: true
    pagetitle: "{{< meta title >}} | Stephanie Cheng"

execute: 
  freeze: auto
  cache: true

